[project]
name = "scudo-mmindl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "marimo>=0.19.7",
    "pyzmq>=27.1.0",
]
